language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: ls97yhjHOr5A4KKYiSAPuIlBsZI+32L1f3HnHknfrVrgyVI7YpwW1e6b8pzKlQ5jbd18nkXrPc42W9nOyCWNhlOIsfpM7ayBSB85oiY157BG4pzaTRxfE4dvlt2ZVzcKQPtV2QaZyuy5piQBxgp/+E4oiaFZeXVquQfXOBSn5X+8wBNWtS4I1bub1TKK9VDhodya6biemydWFBcCoVJk/clyiFmvpkNmIYN6viwFtkDstaGmAw/p8X/utnxpEfOqcXJf57Dd7bnpC8lhT3B5ot6XFI7mi6Po/cabcKZs8akYU97xNkdCKN+sD/IDbgZXOnnZ21/zdSIrrtRxAZnxVjcE8sphNr/S7UJppHFj6+4Yu/209GesiHWLKc91ZVtLYvbU+RJgXbN0J88SabtxDZlmznNOb0RY9j99/xvnLM9XyBlpRxLK0qk4dlIhkOceAPjFd/tksZeBC61kEeFFB5pEyOZFAkCJTwSJf4d79WpwuNA0H+VDhqsqJomdcmVu9dG9cdR8Z1IYwr505ymEUrLsOp/iJNmPpOZxpdnyy81brC/g4nB10oqoU/h0eUOIVyLFnUv/V8JXNTPPyR63E6Udv57arEzJ6FAklIbLzF58Qw2BGpB833cOPi2zk4VI2lco4B/EPU4PAx2TL5xoIhFH9LCWIqMxzXNgkagFcx8=
  app: obscure-hamlet-23694
  on: 
    repo: lightsage88/react-hot-cold-travis-heroku
